# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce2ade2c01d933f96e4adac747ececc994063065390908d4cb527960a668a1d9107f04a9b024935e320b85811b2fc4585ca6de99a73e60ffbec04f352eeb4beb

test:
  secret_key_base: 7ab6d98f23a82ec0199bab04760e6ffea230eb6d233a58ebf2f9eec90c8b0d0aabc2bd8a4ba273b32d5d3c67f13072f7c4b912edb40805f384d19146efb96c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
